spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/duneinsolite
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: duneinsolite
    password: duneinsolite123
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          initial-interval: 5000
          max-attempts: 3
          multiplier: 2

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/duneinsolite

keycloak:
  admin:
    server-url: http://localhost:8180
    realm: duneinsolite
    client-id: duneinsolite-api
    client-secret: DzXfwEHyTCynUJtKevpCXlz5yVtBBUYK
  realm: duneinsolite

server:
  port: 8080